version: "3.7"
services:
  nginx:
    image: vp_nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my_network
  
  fastapi:
    image: fastapi_token:latest
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_token/main.py:/app/main.py
    networks:
      - my_network

networks:
  my_network:
